### ISSUE TITLE
delete a file

### ISSUE THREAD

**Issue by Aidatbr** [devilry/devilry-django#1010]
Hello

I have an assignment deadline which is not expired yet. I had submitted a version some days before, however, I decided to add something today, and I uploaded a new version. How can I remove the first submission?

Thank you in advance

**Comment by torgeirl** [comment]
Hi @Aidatbr,

No, by design a student can't delete an uploaded file. Instead, the newest delivery will be the active so the previous deliveries are discarded for examiner downloads etc.

Please note that this Github repository isn't the way to get support for your local Devilry instance. Ie student's at UiO can follow the guide lines here: https://www.mn.uio.no/ifi/tjenester/it/hjelp/devilry/

-Torgeir
