### ISSUE TITLE
Import options for assignment creation

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1021]
In Devilry `2.x`, creating a new assignment allowed you to import students from a previous assignment and gave you the option to limited the import to students with passing grades of that previous assignment:

![screenshot from 2018-04-30 17-41-42](https://user-images.githubusercontent.com/796053/39436400-2a56e308-4c9e-11e8-8f26-f35854fd88c1.png)

This feature seems to be missing in `3.x`. Furthermore, the lack of negative search filters (issue #1015) means the workarounds are fairly time consuming.

**Solution**

- Add an options for student import to assignments.

**Comment by StianJul** [comment]
We already have the import feature, but it's a "bug" when creating an assignment and the workflow for adding students is not optimal.

We should not add students automatically to a new assignment. When creating a new assignment, the user should be taken directly to the view for selecting students from previous assignments on that semester, instead of the assignment detail view.

The user should be redirected to this view after creating an assignment: 
![screen shot 2018-05-08 at 09 36 12](https://user-images.githubusercontent.com/3988175/39744072-4caae9c6-52a3-11e8-952f-658588aaa388.png)

The current state takes the user to the assignment overview and adds students automatically. If no students exists, the "Add students" button takes the user to the manual user select view (which is wrong):
![screen shot 2018-05-08 at 09 40 02](https://user-images.githubusercontent.com/3988175/39744221-d3811dda-52a3-11e8-9215-8af3217d233d.png)


Workflow:
1. User creates assignment
2. User is redirected to view where students can be selected from previous assignments(or manually selected)
3. The user selects an assignment and finishes the workflow for adding students
4. Is redirected to the assignment detail view

As mentioned at the top, this functionality exists, so we only have to fix the redirects (and not add students autoatically when creating an assignment).

**Comment by torgeirl** [comment]
@StianJul: excellent. :+1:

**Comment by StianJul** [comment]
We have made some changes to this plan. The original plan was to redirect the user to the "Add students" view, which is a subpage under the admin assignment overview(**assignment overview -> students overview -> add students view**). 

This could be a bit disorienting to the user, creating an assignment, then being sent to a subpage and then they need to navigate back to the assignment overview.

The solution that we went for is simply to add all students on the semester when creating an assignment. We also reworked the warnings/notifications, together with simplifying the assignment overview a bit, the image shows the assignment right after it has been created and an examiner has been assigned a couple of students:

![screen shot 2018-06-06 at 10 57 04](https://user-images.githubusercontent.com/3988175/41027868-6e084f96-6978-11e8-830f-f2a000457203.png)

The blue information box at the top has been completely remove and replaced with warnings inside the "Manage students" and "Manage examiners" sections.

**Last but not least**, since we now add all students to the created assignment, we have also added another option for removing students from the assignment. You can still manually select students that you wish to remove, but you can also remove students that failed another assignment on the semester. These are just options added to the old "Remove students" page (**Assignment overview -> Manage students -> Remove students or project groups**):

![screen shot 2018-06-06 at 11 29 53](https://user-images.githubusercontent.com/3988175/41029820-ff071334-697c-11e8-89a8-e3d9ee839f18.png)

**Comment by torgeirl** [comment]
> The solution that we went for is simply to add all students on the semester when creating an assignment. 

@StianJul: I have to check with our administrators, but I think this workflow wouldn't work too well for some of our bigger subjects with multiple administrators. What's the reason for moving away from the original workflow?

> The blue information box at the top has been completely remove and replaced with warnings inside the "Manage students" and "Manage examiners" sections.

Very well! :+1:
