### ISSUE TITLE
Comment editor better suited for math (LaTeX) and programming

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1040]
The current `3.x.x` comment editor has limited support for code blocks, known issues (ie #994), and seems to lack support for math.

We should probably look into alternatives so feedback could contain math like `\[ f(x) = \int_{-\infty}^\infty \hat f(\xi)\,e^{2 \pi i \xi x} \,d\xi \]` (but rendered!) and syntax-highlighted code.

**Some alternatives**
- MathJax
- [KaTeX](https://khan.github.io/KaTeX/) (used by [Rocket.Chat](https://github.com/rocketChat/Rocket.Chat/))
- ++

**Comment by espenak** [comment]
I think this should be solved with a custom markdown tag that converts to a webcomponent that renders the latex using MathJax or KaTeX. KaTeX looks very promising, and we have had some issues with MathJax that lead to it being disabled. This approach is a change from the way we previously used MathJax since this makes it more isolated. We can probably use shadow dom to isolate the CSS etc., and we will avoid get an expensive and error-prone "look for math in the entire comment" flow like we had previously since we will render the web-component ready with the latex as "body" for the element, and avoid any extra client side overhead.

**Comment by torgeirl** [comment]
@espenak: excellent! :+1:

**Comment by torgeirl** [comment]
Solved in Devilry 5.5 (#1174, #1220).
