### ISSUE TITLE
Requirements for the new developer tutorial

### ISSUE THREAD

**Issue by vegarang** [devilry/devilry-django#105]
Add comments about topics needed for the "new developer tutorial".

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
