### ISSUE TITLE
No visual indication of candidate numbers

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1051]
In `2.0.x`, department and subject admins would see the candidate number. It seems to be no visual indication of the presence of candidate numbers in `3.x.x`.

Without it, administrators doesn't have a way to verify that the candidate numbers have been imported before they are needed.

**Comment by Levijatan** [comment]
FIxed is inn branch issue-1051-No-visual-indication-of-candidate-numbers by using the should be anonymous check that already is inn place and adding a check for if assignment has anonymization mode on and if true show anonymous_name (candidate number). Since I am using the check that already checks for role when displaying candidate name this should make sure that only the correct roles can see the candidate_id with the student name. Showing "Automatic anonymous id missing" when id is not set.
