### ISSUE TITLE
Integrasjon med Felles Studentsystem (In Norwegian)

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#108]
Det er flere ting som må på plass for å få til integrasjon med Felles Studentsystem (FS).

IT-kyndige (drift) kan gjøre denne integrasjonen i sitt valgte programmeringsspråk (perl, python, java,....) via våre RESTful webservices (se issue #93). De kan f.eks. synkronisere data med devilry hver natt.

Det som gjenstår er da å vite hvilke data som skal dumpes inn/ut av devilry.

**Data inn til Devilry:**
- Kursinfo: kort navn (f.eks. inf1010), langt navn (f.eks. "Objektorientert programmering")
- Semesterinfo: Start/slutt tid, faglærere(administrator).
- Oppgaver: Studenter, rettere

**Data ut av Devilry:**
- Godkjentstatus på hver enkelt oppgave for hver enkelt student
- Karakterer på eksamen (inkl. hjemmeeksamen)
- Beregning av avsluttende karakter? Før dette kan gjøres må vi ha et grensesnitt for å sette karakterer fra f.eks. to hjemmeeksamener og en avsluttende. (eller midtterm+avsluttende).

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
