### ISSUE TITLE
'Load all' option

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1095]
Long lists of students are just partially loaded, and the only option provided is to load another ten students (`Load more`).

The only problem with also providing a `Load all` option seems to be that Internet Explorer 11 going to have a hard time, so no real reason to not provide it.

**Comment by torgeirl** [comment]
This would requires updates to `django_cradmin` so it probably has to wait for the Python3 upgrades scheduled this fall.

**Comment by StianJul** [comment]
@torgeirl, 

would a possible solution be to, for selected views, only have "Load all" instead of "Load all" *and* "Load more", and instead bump the initial page size to say 20?

**Why?**

`cradmin_legacy` kind of supports this now without too much hassle, other than implementing the support for whether we should load by the given page-size, or all elements.

Adding the "Load all" as an addition to "Load more" would require us to rewrite the old "coffeescript/angular" code to support both functionalities, plus updating the framework for building those listviews.

**Specifics**
For "selected views", I mean first and foremost:
 - Overview of students on an assignment for admins (which is the one talked about in this issue).
   - We bump the page-size to 20
   - Configure the pager to load all elements instead just the next page.
   - This will then show "Load all" instead of "Load more" below the list
 - Overview of students on an assignment for examiners
   - Page-size here is already 20
   - Configure the pager to load all elements instead just the next page.
   - This will then show "Load all" instead of "Load more" below the list
 
We can talk about including this other places as well at later point.

**Comment by torgeirl** [comment]
@StianJul: this solution should cover our use cases. :+1:
