### ISSUE TITLE
Default deadline time

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1102]
The assignment deadline suggestions are currently set to 23:59, but in the date selector defaults to current time.

It would be an improvement if the default was set to 23:59 or a `settings.py` value would allow sysadmins to provide a default deadline time.

**Comment by StianJul** [comment]
Note: This includes fix for https://github.com/devilry/devilry-django/issues/1092 since these are somewhat related.

**Deadline seconds**
This is now cleaned with seconds as 59, meaning that the deadline includes the given datetime, not just up until as it was before. E.g, setting `24. Desember 23:59` will mean that the deadline expires just before midnight, and not one minute before midnight.

**Deadline suggestions Assignments**
We still keep the old implementation of how suggested deadlines are generated when creating an assignment for historical reasons. Deadlines when creating an assignment will be based on the deadline for the previous assignment, meaning that if the first deadline of the first assignment is 23:59, this will propagate to the next assignment when creating it and so on (if not changed for an assignment along the way of course).

**Deadline suggestions Groups**
The utility for moving deadlines and giving new attempts to groups will still give deadline suggestions based on the deadline they're being moved from (or current time if the deadline is in the past), but unlike before, all suggestions will show 23:59 as the time.

**Datetime picker for deadline**
It will still default to the current day (as before), but 23:59 instead of the current time. The user can still change the time to whatever they want, or press the "now" button to get the current time.
