### ISSUE TITLE
Compressed archives aren't dicarded when candidate numbers are changed

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1111]
Compressed archive files are automatically discarded (not re-used) if their content changes (a student upload another file), the requestee's permissions to the student changes (issue #982), and a whole other range of reasons.

For semi anonymous assignments, the directories in the compressed files for admin and examiners are set to the candidate number(s) of the student(s) instead of their user names. It seems we forgot to add candidate numbers changing as a scenario for when to renew the compressed archive files.

**Workarounds**
After overwriting existing candidate numbers with the [`periodsetrelatedstudents` command](https://devilry.readthedocs.io/en/latest/sysadmin/managementcommands.html#devilry-periodsetrelatedstudents) you'll need to delete existing compressed archive files for the admins and each examiners as a superuser.

If you can't be sure the relevant compressed archive files gets deleted, you probably want to go for the nuclear option:

- `venv/bin/python manage.py devilry_delete_compressed_archives --all`

**Comment by espenak** [comment]
For reference: This is the current rules for "recreating" the archive: https://github.com/devilry/devilry-django/blob/c00bd24047d788efe0e3b680faf0c9cbb74f9a06/devilry/devilry_group/views/download_files/batch_download_api.py#L106-L149.

We can not extend this to track changes to candidate ID simply because we do not have enough info to query against. I think the only solution is to delete the archives in the management script used to import candidate IDs (devilry_periodsetrelatedstudents).

**Comment by espenak** [comment]
## Solution
Extend https://github.com/devilry/devilry-django/blob/master/devilry/devilry_superadmin/management/commands/devilry_periodsetrelatedstudents.py with:

- Check if the unique set of candidate_ids for RelatedStudents on the period is changed by the import.
- If so, mark ALL ``CompressedArchiveMeta`` objects within the period for deletion.

Marking for deletion is efficient, and makes the download API ignore them and trigger build of a new archive. As long as the ``devilry_delete_compressed_archives`` management command is run regularly (as it should), the files will be removed permanently after some delay.
