### ISSUE TITLE
Excel files lack file type when downloaded from feedback feed

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1153]
From user report.

Can confirm files lack file type when downloaded from `/feedbackfeed` view, but unable to reproduce.

**Comment by espenak** [comment]
I can not reproduce this. I have tested with both `xlsx`:

![image](https://user-images.githubusercontent.com/84501/111297963-8745c600-864e-11eb-8a81-06b9693fd513.png)

And the old `xls` format:
![image](https://user-images.githubusercontent.com/84501/111298009-94fb4b80-864e-11eb-8367-51e1208bf630.png)

Both result in the correct content-type. We use the built-in python functionality for guessing content-type from file extension, and as expected and according to MDN, they are correct (https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types).

My guess is that this is caused by uploading an excel file without a `.xlsx` or `.xls` extension. We do not and will not parse the file content to guess the content-type.
