### ISSUE TITLE
Assignment statistics incorrect with multiple examiners

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1198]
The assignment statistics re-introduced in `3.4.2` (issue #1042) calculate points, result/progress, corrected groups etc by looking at students assigned to an examiner. This is completely invalidated if multiple examiners are assigned to a student.

**Example**
- five examiners are assigned to all 250 students on each assignment, leading to every examiners' average feedback length being the same, etc

**Suggested solution**
Calculating the statistics based on who provided the feedback and grade/points. The assignment statistics probably should be divided into first attempt, second attempt, etc, and last attempt (last being final result).

**Comment by StianJul** [comment]
@torgeirl, I see the problem here, but this is not as much a bug as it is the wrong way of crunching the numbers given how the examiners are actually assigned to the groups in this case.

The implementation is based on the assignment groups, and the assumption here was simply that multiple examiners assigned to a group is "collaborating" on the grading, thus giving the same credit to the involved examiners. Of course, this doesn't work when all examiners are assigned to all assignment groups so that it's, from the systems point of view, no way of deciding which examiner is responsible for which assignment group and their progress at any given point (except assuming all examiners for the assignment group is involved).

The sections **"Points (average)"**, **"Result / Progress"** and **"Details"** are all based on the assignment groups the examiners are assigned to, and not the actual action taken by each examiner (since it's assumed that examiners within the same assignment group is collaborating). And this obviously doesn't show the desired statistics in this case since all examiners are essentially "collaborating" with each other on every assignment group.


### Proposed solution

Gather the statistics as proposed in the issue, that we actually only consider the action taken by each examiner, potentially disregarding all other examiners assigned to the group. We need to clearly define how this should be produced, and possibly redesign how to present the statistics if we should also take into account every attempt-grading and not just the last final grading (which depends on each assignment group).


### Alternative solution

We keep the statistics as is, based on the assignment group, and introduce a feature to enable proper first-come-first-serve where examiners assign themselves to the assignment groups with some basic rules at least, such as that an examiner can only select an assignment group without examiners assigned, and that the examiner can only have a total number of assignment groups at any given time that are not graded etc.


Above are at least two possible solutions, but other suggestions are welcome. Either way, I think we should have a meeting to discuss this further.

**Comment by torgeirl** [comment]
@StianJul: moved this to the next milestone awaiting a discussion. :+1:

**Comment by torgeirl** [comment]
> **Suggested solution**
> Calculating the statistics based on who provided the feedback and grade/points. The assignment statistics probably should be divided into first attempt, second attempt, etc, and last attempt (last being final result).

After looking more into the usage paths that lead to this being an issue we have ended on a different solution:

**Suggested solution**
When one or more students have more than one examiner assigned, a warning will be displayed on the statistics page:

> WARNING: This assignment has student groups with multiple examiners assigned to them. Multiple examiners are assumed to be collaborating on the grading, thus giving the same credit to all assigned examiners regardless of who added the grade or posted a feedback to the student group.
