### ISSUE TITLE
Too low contrast for role selector boxes

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1206]
Success Criteria 1.4.3 in WCAG 2 requires that the visual presentation of text and images of text has a contrast ratio of at least 4.5:1.

When hovered, the contrast for the text on the role selection boxes (Student, Examiner, Administrator) falls below that threshold.

**Comment by espenak** [comment]
## Step 1 - font that is not as light
(light fonts require more color contrast to be readable)

Before:
![image](https://user-images.githubusercontent.com/84501/151530131-40b3937f-a837-422a-ac71-8c1005cc849a.png)

After:
![image](https://user-images.githubusercontent.com/84501/151529984-4d9eb61f-60e1-49cf-810f-d3677bb68840.png)

**Comment by espenak** [comment]
## Adjusted colors
I have adjusted the theme colors, and added a wcag debugging view.
![image](https://user-images.githubusercontent.com/84501/151562715-c3d40299-75e3-487e-b2ef-d6f5cfb64939.png)
(just ignore the two first entries in the wcag contrast checker, those are some hidden angular keymap helper elements).

### More examples
![image](https://user-images.githubusercontent.com/84501/151563031-5f51c363-abb3-461f-9c2d-fcd0651e0dd2.png)

![image](https://user-images.githubusercontent.com/84501/151563246-90f89db5-eeb0-4c35-8ba0-2fb9c3e425df.png)


![image](https://user-images.githubusercontent.com/84501/151563093-c6f7d55b-339e-4c0f-a15f-a3cac9cab95b.png)

![image](https://user-images.githubusercontent.com/84501/151563163-ce05ac9f-129f-4f74-bc82-086d592dc576.png)

**Comment by espenak** [comment]
I have performed a lot of checks now, and with the changes made so far, we have contrast at AAA level for a lot of the content, and well withing AA level (>5:1) for the things with a colored background.

Getting the things with colored backround up to AAA levels is possible, but it will require rethinking how we use colors since the backgrounds will become very dark. May consider swapping to very light color hints (light green, light blue, etc.). In any case, that will be a milestone in itself if we want to do it.
