### ISSUE TITLE
Unclear purpose of archive download link

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1209]
WCAG 2.1 Success Criterion 2.4.6 (Headings and Labels) requires that headings and labels have a described topic or purpose.

The purpose of the the link for building the archive file is unclear. The link descriptions for all students on one assignment, from an admin's perspective:
- No prebuilt archive file available (`devilry-batchprocessed-download devilry-batchprocessed-download--not-created`): «Download assignment»
- While building the archive file: «*wheel* preparing download»
- When an archive file is available (`devilry-batchprocessed-download devilry-batchprocessed-download--finished devilry-batchprocessed-download--finished-within-same-session`): «download is ready \n Download assignment»

The archive file links in the feedback feed will instead have link descriptions such as «first deadline», etc.

Using a screen reader it is not very clear what these links do at different points.

**Comment by StianJul** [comment]
Added aria-labels with a clearer description regarding the various states of the file-archive download "button". `aria-live="polite"` has been added to the element surrounding the button to notify the screen-reader about changes.

### Feedbackfeed
#### File-archive built and ready for download

- Link focus: "Download <first|second|etc deadline> file-archive"

#### File-archive must be built before download

- Button focus: "Build downloadable file-archive for <first|second|etc deadline>"
- Button click: "Preparing download"
- When download is ready (changes in the download file-archive button, due to `aria-live`): "<first|second|etc deadline> file-archive ready for download"

### Assignmnet/group overview (admin/examiner)
#### File-archive built and ready for download

- Link focus: "Download assignment file-archive"

#### File-archive must be built before download

- Button focus: "Build downloadable file-archive for assignment"
- Button click: "Preparing download"
- When download is ready (changes in the download file-archive button, due to `aria-live`): "Assignment file-archive ready for download"
