### ISSUE TITLE
Option that allow examiners to self-assign assignments

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1218]
As part of the discussion regarding #1198 (Assignment statistics incorrect with multiple examiners) we re-visited the causing user pattern: allowing examiners to self-assign assignments with self-paced student progression.

**Suggested solution**
* New option on each assignment: allow examiner to self-assign student groups (default: false) and max self-assigned examiners per student group (default: 1)
* Add a subject filter to the examiner dashboard
* when deliveries on a self-assignable assignment are `waiting for feedback` and number of examiners is lower than the set max the examiner dashboard for examiners on the assignment's semester gets a new view that lists the available assignments (default sort: delivery in chronological order)
* in the new semester self-assign view, the default sort should probably be deadline then students' upload time

**Nice-to-have**
* Extra filter in the semester self-assign view: filter self-assignable assignments to a set of assignments (user case: «show student groups on Assignment D, F and H as I'm currently focused on their curriculum»)

**Comment by StianJul** [comment]
@torgeirl, we now have an "mvp" for the self-assign solution. The current solution is simple and functional, but not too specialized yet. What I mean about not being specialized, is that the rules aren't that strict when it comes to which projectgroups should be shown (we instead just provide the existing filters examiners are used to). I think this is where we should start, and update this feature incrementally as we get feedback on this functionality.

**Note:** Self-assign is not available for anonymized assignments. The reason for this is that we don't have a projectgroup search-filter for examiners when projectgroups for anonymized and non-anonymized assignments are listed (since this is a entirely new use-case). Possible solutions  to this is:
- Keep as is - self-assign won't apply for anonymized assignments.
- Support anonymized assignments - remove search-filter for examiners
- Support anonymized assignments - implement search filter that filter different fields for the projectgroups based on the assignments anonymization mode.


**Rough description:**
- Admins can enable disable the self-assign functionality for each assignment.
- Examiner-dashboard will show a box with links to the self-assign view for each active semester that has published assignments with self-assign enabled.
- Examiner self-assign view will only show groups the user is already examiner for, or where the examiner self-assign limit is not reached.
- The projectgroups are ordered by deadlines in ascending order.
- Each projectgroup is shown with a button for the examiner to assign/unassign themselves from the projectgroup

I've provided a few screenshots, to make it easier for you to provide some feedback before we release it!

## Admin screenshots
![Screen Shot 2022-05-19 at 11 49 25](https://user-images.githubusercontent.com/3988175/169265610-4bc0f9e4-80c3-4ab3-9f3d-f33202e67957.png)

![Screen Shot 2022-05-19 at 11 50 12](https://user-images.githubusercontent.com/3988175/169265638-f9a562e4-90a9-4319-846d-cbc87f8d152a.png)

## Examiner screenshots
![Screen Shot 2022-05-19 at 11 51 33](https://user-images.githubusercontent.com/3988175/169266240-7edc1e9b-b15b-4005-83e7-d96d62736ad3.png)

![Screen Shot 2022-05-19 at 11 53 17](https://user-images.githubusercontent.com/3988175/169266315-83edc0bf-d099-4ea1-b8e2-531be123d4d2.png)

**Comment by torgeirl** [comment]
@StianJul: this looks like an excellent first implimentation! :+1: 

> **Note:** Self-assign is not available for anonymized assignments. The reason for this is that we don't have a projectgroup search-filter for examiners when projectgroups for anonymized and non-anonymized assignments are listed (since this is a entirely new use-case). Possible solutions to this is:
> 
> * Keep as is - self-assign won't apply for anonymized assignments.

I say we keep it as-is, and that we instead should make sure to point out why it can not be activated (unsupported) in the UI.

**Comment by StianJul** [comment]
![Screen Shot 2022-05-19 at 12 41 26](https://user-images.githubusercontent.com/3988175/169275319-1ee587d8-c1b5-46ee-aa16-bade5cf4d0d0.png)
