### ISSUE TITLE
github pages

### ISSUE THREAD

**Issue by rebekkjm** [devilry/devilry-django#123]
Learn how github pages and Jekyll work. We can use github pages for the devilry website.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
