### ISSUE TITLE
`diffwrapper`'s tabs doesn't work for previews

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1235]
It isn't possible to switch from Simple diff to Compact or side-by-side diff when previewing a comment. Switching works for the published comment.

![Screenshot from 2022-08-12 12-58-13](https://user-images.githubusercontent.com/796053/184340967-3be826e4-e36b-413e-a187-42e4e24226b6.png)

**Comment by espenak** [comment]
This is documented in the documentation.
![image](https://user-images.githubusercontent.com/84501/190628881-92a684ff-d84f-4656-ba13-a1daa9caa3f2.png)

It is not possible to preview this because of how the preview is rendered (it can not execute dynamic javascript). We CAN probably fix a message about this in the actual preview, but we can not make this work. The way to preview the different diff styles is to send the default style argument in the markdown. E.g.:

```
##<## compact
def Hello(self, x):
    print(f'Hello')
    print('World')
##>##
def hello(self, x):
    print(f'Hello {x}')
    print('World')
##<##
```
(default to ``compact`` mode, and that works in the preview)
