### ISSUE TITLE
An assignments publishing date

### ISSUE THREAD

**Issue by ctryti** [devilry/devilry-django#124]
An assignments publishing date can be set to a date before or after it's periods duration. 

There should be some validation to avoid this.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
