### ISSUE TITLE
integrating testcoverage

### ISSUE THREAD

**Issue by vegarang** [devilry/devilry-django#125]
Looked into integrating [coverage.py](http://nedbatchelder.com/code/coverage/) to see how much of the devilry source code our tests cover. This worked with no big problems, the only issue was to create a file [.coveragerc](http://nedbatchelder.com/code/coverage/config.html) specifying the directories coverage.py should test to avoid coverage from testing Django as well.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
