### ISSUE TITLE
Assign students to examiners by weight

### ISSUE THREAD

**Issue by rakfisk1** [devilry/devilry-django#1272]
In many cases examiners should be given a different amount of students to grade. It would be helpful with a function that allows you to randomly distribute students to examiners, but give each examiner a weight that gives them more or fewer students to grade. 

Example: Say you have an assignment where 100 students have handed in a delivery. You have 3 examiners. One of them has twice as many hours per week to grade as the other ones. 

It would be helpful to be able to assign a relative weight of 2 to this examiner so that he automatically is assigned 50 students to grade and the other two get 25 students to grade.

**Comment by torgeirl** [comment]
@rakfisk1: thanks for the suggestion!

It is however a duplication of an existing issue: «Random distribute with selectable count per corrector» (issue #901). The issue is old (December 2016), but I've kept it open while closing hundreds of other old issues since it is still something we would like to address.

It is however lower on our list of priorities, and to due to limited resources I can't say when - if ever - we get to it.

Closing this duplicate.
