### ISSUE TITLE
StaticFeedback.saved_by can be set to any User

### ISSUE THREAD

**Issue by ctryti** [devilry/devilry-django#128]
Any User-object can be set as a StaticFeedbacks creater (saved_by).

This field should probably only be one of the examiners in the graded Delivery's AssignmentGroup.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
