### ISSUE TITLE
Handling multiplie deliveries

### ISSUE THREAD

**Issue by rebekkjm** [devilry/devilry-django#129]
Before a deadline students can make as many deliveries as they like. However, this can create a problem for the examiner, who prefers to look at only the latest delivery. If this delivery doesn't contain the whole assignment the examiner has no way of knowing if the student has only answered part of the assignment, or if the rest is in a previous delivery (without checking previous deliveries  - very time-consuming)

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
