### ISSUE TITLE
Requirements clean-up

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1299]
When installing Devilry via PIP for production, quite a few of its dependencies seems to only be relevant for development or no longer needed at all.

**REMOVE**
- detektor
- dj-database-url ([Django's `DATABASES` config](https://docs.djangoproject.com/en/4.2/ref/databases/) solves this by itself)
- dj-static ([deprecated](https://github.com/heroku-python/dj-static); sysadmins can use WhiteNoise for static files)

**MAKE DEV ONLY**
- ievv-opensource (both directly and via `cradmin-legacy`)
- Sphinx (via `cradmin-legacy` -> `appresso-sphinx-extensions`/`appresso-sphinx-extensions`)
- tox (via `cradmin-legacy`)

**Comment by espenak** [comment]
I have cleaned up dependencies in cradmin-legacy (relasing it soon). I no longer pulls in pytz, tox, sphinx, solr-thumnail and Pillow by default.

**Comment by Levijatan** [comment]
I have gone through the dependencies and there where a few that was not used. Using deptry I have found:

- pyyaml (Not Used)
- flup (Not Used)
- URLObject (Not Used)
- mimeparse (Not Used)
- numpy (Not Used)
- pytz (Not Used)
- httplib2 (Not Used)
- html5lib (Not Used)
- django_cradmin(Also from cradmin_legacy with the same requirements)
- chardet(Not Used)
- idna(Not used directly. Also from request with the requirements <4, >=2.5)
- oauthlib(Not Used)
- python-openid(Not Used)
- request-oauthlib(Not Used)
- urllib3(Not used directly. Also from requests with the requirement <3, >=1.21.1)
- six(Not used directly. Also from python-dateutil with requirement >=1.5)
- python-dateutil(Not used directly. also from arrow with requirement <0.13.0,>=0.12.0)
- pygments(Not used directly. via cradmin-legacy, django-cradmin, apresso-sphinx-extensions from sphinx with requirement >= 2.14)

Removed the ones that are not used. Removed python-dateutil, idna, django_cradmin and six since their requirements are equivalent or stronger in other dependencies. Kept urlib3 since our has a slightly higher lowest version requirement, probably not necessary. Created 2 new optional dependencies categories one for docs and one for the internal production setup. Is the internal production setup even used?

Moved openpyxl, htmls, dj-database-url to dev, dj-static to prod. Added doc2dash, Fabric3, sphinx, and sphinx_rtd_theme to docs.

Added a small fix to comply with "newer"(>=18) pycontry to allow it to not have as rigid version requirement

Removed version requirements for xlsxwriter, it seems to be working perfect.

Removed detektor

Could not move ievv_opensource since it is used in for some batch operations and for some registry singletons. The registry singletons should be realy easy to decouple from ievv_opensource. But for the batch operations I am not so sure.

Relaxed html2text requirements, since it is only used in one place and i could not find anything breaking in its release notes.

commited the updated pyproject.toml inn 6c3d141

**Comment by espenak** [comment]
Moving this to 6.3 milestone and cherry-picking it into master to avoid problems/conflicts with #1290.

**Comment by espenak** [comment]
I do not think we should remove dj_database_url. It is a well maintained [12factor](https://www.12factor.net/backing-services) library that leads to cleaner prod configuration through environment/secret stores etc. It makes it easy to adjust database connection settings via one single URL etc.

**Comment by espenak** [comment]
> I do not think we should remove dj_database_url. It is a well maintained [12factor](https://www.12factor.net/backing-services) library that leads to cleaner prod configuration through environment/secret stores etc. It makes it easy to adjust database connection settings via one single URL etc.

Never mind - we do not need it as a hard dependency - it can be added via requirements.txt if needed/wanted in prod.
