### ISSUE TITLE
Option for signing URLs using a dedicated IAM

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1318]
Support for presigned URLs were added in v6.3.5 (#1302), and it works as intended. To use it with our S3 provider we do however need that the signing itself is handled with a dedicated «signing IAM» that only handles that part of the process.

Looks like this is something that could be added using `boto3.client.generate_presigned_url()` ([docs](https://github.com/boto/boto3/blob/1.35.8/docs/source/guide/s3-presigned-urls.rst)).

**Comment by espenak** [comment]
@torgeirl releasing the fix for this now. I solved it by making it possible to configure extra storage backends for generating the presigned URLs.

I have added a bit of docs/hints here: https://github.com/devilry/devilry-django/blob/bdc1f642fefb3a8c7bcfb0e29a3f8ddb280868e8/not_for_deploy/docs/sysadmin/gettingstarted.rst?plain=1#L254-L261

And there is a full example in develop settings: https://github.com/devilry/devilry-django/blob/bdc1f642fefb3a8c7bcfb0e29a3f8ddb280868e8/devilry/project/develop/settings/develop.py#L284-L357 (but that uses the same access/secret key in the ``*_generate_urls`` entries in ``STORAGES``). The idea is simply to have extra storage backends that targets the same bucket, but with different credentials..

**Comment by torgeirl** [comment]
With `DEVILRY_USE_STORAGE_BACKEND_URL_FOR_FILE_DOWNLOADS = True` the files are presigned correctly, but it gets served as it is stored (integer as filename; no file type suffix).

**Comment by torgeirl** [comment]
> With `DEVILRY_USE_STORAGE_BACKEND_URL_FOR_FILE_DOWNLOADS = True` the (non-Tar) files are presigned correctly, but they get served as they are stored (integer as filename; no file type suffix).

Moved to separate issue, under v6.4.
