### ISSUE TITLE
coverage crashes because of nonexisting files

### ISSUE THREAD

**Issue by vegarang** [devilry/devilry-django#132]
the Coverage.py script sometimes complains about files that does not exist at a certain path, and never have. 

A google search showed that this is sometimes related to leftover .coverage, *.pyc, *.swp and other config/temp files. All these files should be deleted by 'git clean -dfx' but I still got the error. 

As of now Ive not found a good fix for the problem, and it seems to be a problem with Coverage itself. A temporary fix is the '-i' flag in coverage, as this makes coverage ignore those errors.. 

I added the '-i' flag to the scripts using Coverage, and it works fine for now, but we should find a better solution.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
