### ISSUE TITLE
History for examiners

### ISSUE THREAD

**Issue by rebekkjm** [devilry/devilry-django#133]
How should history be handled for examiners? Should deliveries an examiner has corrected in previous periods be available? Probably not, however it would be useful for examiners to have stats about previous subjects/periods available.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
