### ISSUE TITLE
Updating an existing node

### ISSUE THREAD

**Issue by rebekkjm** [devilry/devilry-django#136]
When using the update()-method in the restful api it should be possible to update an arbitrary number of fields (and particularly only one field!). This is not the case - when updating a node one has to provide both a new long_name and short_name

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
