### ISSUE TITLE
Functionality to delete or hide feedbacks

### ISSUE THREAD

**Issue by bendikro** [devilry/devilry-django#139]
Letting examiners delete feedbacks might be troublesome as situations could occur where the student is given a feedback, and then later on that feedback is changed/replaced by another.
Preventing feedback deletion could also cause problems where wrong info, e.g. feedback for another student was inserted by a mistake. So maybe it should be possible to delete or hide feedbacks. Maybe only administrators should have these permissions, or maybe it should be configurable so that examiners only are allowed to perform these operations.

Proposal1:
- Noone can delete Feedback
- Adminsitrators can hide feedbacks
- Examiners can not hide feedbacks and has to make a request to an administrator 

Proposal2:
- Options can be set to allow adminstrators and/or examiners to delete or hide feedbacks.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
