### ISSUE TITLE
devilryclient: Support non-python plugins

### ISSUE THREAD

**Issue by ctryti** [devilry/devilry-django#154]
Should we be able to run other types of plugins, i.e shell-scripts, java-programs, c-programs, etc?

Not sure if we'd need to specifically support each language (hardcode into cli.py), or if there's a way for plugins to specify how they should be started.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
