### ISSUE TITLE
Auto-complete locks keyboard

### ISSUE THREAD

**Issue by Sardtok** [devilry/devilry-django#155]
When using auto-completion with devilryadmin.py, the shell stops reacting to the keyboard if you double-tap tab when there's a single completion.
For instance if you type devilryadmin.py e and press tab twice, it's impossible to erase or change the command and or parameters. Ctrl-C will stop the script (actually it seems it starts executing cmd_exampledb_generic_scenario.py, but instantly aborts it with a keyboard interrupt).

It seems like devilryadmin.py starts executing commands upon the second tab, at least if it's a database related command like exampledb_generic_scenario or update_simplifiedfixture. Some simple commands like todolist simply lags for a short while (probably executes, but finishes relatively quickly) and releases the keyboard.

**Comment by Sardtok** [comment]
Is this still an issue?

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
