### ISSUE TITLE
Export of students with no deliveries

### ISSUE THREAD

**Issue by rantonse** [devilry/devilry-django#175]
I would like to export a list of all the students with no deliveries for a particular assignment (or a set of assignments). How can I do this (without copy/paste and emacs)?

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
