### ISSUE TITLE
Automatically detect delivered in a previous period

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#176]
We should be able to automatically detect assignments delivered in a previous period. However this needs to consider that some subjects change the setup from period to period, so the first assignment from 2011, may not be the equivalent of the first assignment in 2012. Furthermore, assignments may not be using the same grade editor with the same grade plugin. One solution would be to build this into #167.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
