### ISSUE TITLE
Number of deliveries in admin interface

### ISSUE THREAD

**Issue by ilmarw** [devilry/devilry-django#179]
In the administrator interface, many students are marked with a huge number of deliveries, all in multiples of 14: 14, 28, 42, 56. When opening them in the examiners interface, the number is in fact modulo 14.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
