### ISSUE TITLE
Regex-filter

### ISSUE THREAD

**Issue by trondth** [devilry/devilry-django#183]
The filter is fast and effective, but I would love to have a regex-feature there.

The reason is that I would like to get the list of the students in my «teaching group», and see who what problems there are in mye group (...since I correct a random group). With a regex-filter, I could do like this:

(username1|username2|username3)

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
