### ISSUE TITLE
Feature request: lock file names

### ISSUE THREAD

**Issue by ilmarw** [devilry/devilry-django#186]
It would be nice to be able to lock the file names of uploaded files. In this way, it would be much simpler to script the directory resulting from 'Download all deliveries'.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
