### ISSUE TITLE
Flere konfigurerbare meldinger

### ISSUE THREAD

**Issue by pstray** [devilry/devilry-django#189]
Fikse så "You are not a student" og andre slike meldinger blir litt enklere konfigurerbare.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
