### ISSUE TITLE
Feature request: view as foo

### ISSUE THREAD

**Issue by pstray** [devilry/devilry-django#205]
As an admin, I would like the ability to view the webapp as a given user.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
