### ISSUE TITLE
Solutions available in Devilry

### ISSUE THREAD

**Issue by kinevl** [devilry/devilry-django#219]
It would be practical to publish solutions to exercises in Devilry so that the examiner can refer to that instead of writing extremely long feedbacks. 

Some courses practice giving the same exercises year after year, so it would be necessary to prevent downloading and copying (the only possible way to "copy" it would have to be to print screen), and students will have to sign in to get access to them.

We're still pretty unsure about even publishing solutions to exercises digitally, but if we could get a sufficient way via Devilry, that would be great.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
