### ISSUE TITLE
Recursive publish and feedback in the CLI

### ISSUE THREAD

**Issue by larsjr** [devilry/devilry-django#22]
It should be possible to send and publish feedback for all subfolders in an assignment folder.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
