### ISSUE TITLE
Go over all TODO: delete this? in the core

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#234]
These are methods that we where careful about removing, however some of them are commented out, and other are in active use, so we should do a cleanup of this.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
