### ISSUE TITLE
Charting for periodoverview

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#239]
We should use charts to enhance the overview provided by the grid in the periodoverview. For qualfiesforexam, this can be a cake-diagram. We may also want to chart total points and individial assignments. When #237 is complete, it will probably be useful to be able to make a chart showing the distribution of grades.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
