### ISSUE TITLE
Let students track their own progress in a period

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#240]
At least give them an overview of all their assignments, and any labels that they have permission to view.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
