### ISSUE TITLE
Custom view configs for viewing a special label i periodoverview

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#242]
Hide sidebar, show minimal view, and only a specific label. This could be added as a menuitem on the periodoverview button (make it a split button). The use-case is for the people who are only interested in a specific label/group of labels, and not how they are calculated (such as administrations registering people for exams).

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
