### ISSUE TITLE
Tagginig of late deliveries in the CLI

### ISSUE THREAD

**Issue by fredva** [devilry/devilry-django#27]
There is no way to see in the CLI if a delivery has been delivered after deadline. Hence, you must always have the web interface open as well, just to check this.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
