### ISSUE TITLE
Workflow and UI for project assignments

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#275]
What separates a project assignment from a _normal_ assignment:
- They usually allow cooperation. #274 should make this easy to administer.
- They often want to name the project (using the `name` attribute of _AssignmentGroup_).
- They want to see students that are working alone.

I believe these features are enough to be confusing to users who do not need them. I propose that we add a `is_project_asssignment` attribute to _Assignment_ that the UI can use to determine the options/tools that should be available on assignments.
## Smart detection

It should be possible to set `is_project_asssignment` manually, however I think it should be set to `True` automatically the first time an administrator merge multiple AssignmentGroups into a single AssignmentGroup (i.e.: when they allow cooperation). They should get a notification that tells them that this change was made, what it means, and how they turn it off.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
