### ISSUE TITLE
Maximum length of assignment group names

### ISSUE THREAD

**Issue by rotunda** [devilry/devilry-django#283]
When trying to add a group with name longer than 30 characters, it fails and the error message states incorrect username as the most probable reason. Also, it would be nice to have this length limit in the help panel (on the right, in the group creation wizard).

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
