### ISSUE TITLE
A way for system admins to see current settings

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#3]
We need a app where system administrators can see current settings. This is because it is difficult to debug in a production environment with apache and mod_wsgi when you do not even know if mod_wsgi have loaded you current or your previous settings.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
