### ISSUE TITLE
Candidate ID editor

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#327]
We should have a candidate ID editor on an assignment. This is in 1.2.1 because importing from period should be enough for 1.2 (and most use-cases). I think this should be very similar to the related students grid (show user-info, and a column where you can edit candidate ID). Should support bulk import from CSV (`<username>,<candID>`), and import from period (related students).

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
