### ISSUE TITLE
Purge unsuccessful deliveries

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#336]
We should have an sysadmin script that removes all unsuccessful deliveries. We have considered doing this automatically in one of the following places:
- When a student makes a delivery, remove all their unsuccessful deliveries.
- When a student makes a delivery, remove all unsuccessful deliveries older than one hour (or some sane timelapse).

The problem with both of these approaches performance. We do not add anything that can slow down making deliveries.

This leaves us with some kind of batch-job that takes care of the cleanup. Since we do not (yet) integrate any batching server, this must be a command-line script that the sysadmin can run manually, or as a cronjob.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
