### ISSUE TITLE
Unsuccessful deliveries are counted in summary-grids for examiner and admins

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#337]
When a student starts making a delivery in Devilry (when the first file is uploaded), a delivery is created in the database, and this delivery is marked as unsuccessful. The API used by the examiner interface in version 1.1 counts any deliveries, not just successful. Fixing this is not a simple matter, so the issue will remain until we can replace that API.

The API has already been replaced for administrators in version 1.2 (not released at time of writing). The API was replaced for students in version 1.1.

See also: #336

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
