### ISSUE TITLE
Topic guides for subjectadmin

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#359]
We should have some topic guides for the new subjectadmin UI. These guides should highlight common use-cases that Devilry solves. These guides will typically be for things that users may not expect the system to be able to solve, so they may not even consider using these features unless we help them discover them. Suggested topics:
- How to make sure all students get good feedback - using a combination of #300 and #302.
- How to handle weekly deliveries efficiently.
- ~~Overview of the different roles in Devilry.~~
- How to handle giving students another chance after failing an assignment (this is only information to administrators, since examiners handle this).

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
