### ISSUE TITLE
Extracting an all-file download with Ark and Archive Manager fails when files have Norwegian characters

### ISSUE THREAD

**Issue by dragly** [devilry/devilry-django#361]
There seems to a problem when files have Norwegian characters such as "æøå" in them and you select to "Download all files (.zip)". On Ubuntu using either Ark or Archive Manager, such characters show up as ?? and the files fail to extract with the following error message:

"caution: filename not matched:  something-norwegian\?\?.pdf"

This error does not occur if all files are extracted at the same time, indicating that there might be a bug in Ark and Archive Mounter, but I'm thinking that an encoding change (or enforcing non-ascii characters) could fix this problem.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
