### ISSUE TITLE
Examiners and admins can add feedback to unsuccessful deliveries

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#362]
Examiners and admins can use the detailed student overview to add feedback on students without any successful deliveries. This causes students to get feedback that they can not view because, from their perspective, the delivery does not exist.
## Why do admins and examiners see unsuccessful deliveries?

See #337
## How does it happen?

Deliveries are created when a student uploads a file. If they never click "Finish delivery", the delivery is never marked as successful.
## What to do with affected students?

We will create a management script that a system admin can use to manually set deliveries to successful.
## Suggested patch

Fix #337, and throw an exception if a feedback is added to an unsuccessful delivery.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
