### ISSUE TITLE
<new feature> :mulighet til å skrive tekst sammen med innleverte filer

### ISSUE THREAD

**Issue by Nitedal** [devilry/devilry-django#41]
Hadde vært fint om vi kunne skrevet inn tekst til å kommentere innleveringer samtidig som vi lastet opp filene. Slik at vi kan skrive en 5-6 linjer med kommentarer som ikke er en del av selve den innleverte filen. Skriften bør bli synelig før den som retter åpner filen.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
