### ISSUE TITLE
Allow examiners to upload deliveries for their students

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#423]
This is useful in these cases:
- Students have problems with Devilry, and naturally fall back on using email.
- Students have added the delivery through the wrong delivery system - quite a common occurrence.
## Suggested by

This issue was suggested by Pierre Lison.

**Comment by torgeirl** [comment]
We very rarely experience that student deliver on the wrong assignment (probably since the current user interface sort assignment in the student dashboard by upcoming deadline) and if so I don't think allowing examiners to upload on the student's behalf would be a good solution. Closing as this no longer seems relevant.
