### ISSUE TITLE
Document file upload size limits

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#440]
Since Devilry uses Django, there is no file upload size limit as far as I know. But some proxy servers may have one configured. We should:
- Document how to set this in the most common servers (Apache, Nginx)
- Add a setting that we can use to show better information about max file size to users.

**Comment by torgeirl** [comment]
The sysadmin docs now [covers how to set this for Nginx](https://devilry.readthedocs.io/en/master/sysadmin/webserver.html) (`client_max_body_size`). Default file size limitations wasn't an issue with Apache while we used it.

As we discussed in issue #958, a setting to show better information about max file size to users might still be needed.

Closing this issue since the remaining problems from this issue seems to be covered by #958.
