### ISSUE TITLE
Search plaintext deliveries (sourcecode) for predefined patterns

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#53]
Examiners and admins should be able to define sophisticated (regex?) and simple patterns tied to a assignment, which helps them with the examination.

An example would be if a student is supposed to implement a specific feature in a C program; lets say ACK in a network protocol. If the examiner defines a case insensitive search for "ack" in all .c and .h files, they would get a box on each assignment showing matches, and links directly to the line with match. We might even embed the lines around the match in the box.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
