### ISSUE TITLE
Supplying some files to all deliveries in a group / assignment

### ISSUE THREAD

**Issue by lstor** [devilry/devilry-django#66]
Functionality should be added to add one or more files to the directory structure generated for each group's deliveries in an assignment. For example, automatically add the file "UseThis.java" to the group's code.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
