### ISSUE TITLE
Add logic to prevent multiple deliveries within a short period of time

### ISSUE THREAD

**Issue by bendikro** [devilry/devilry-django#69]
There is no limit on the number of deliveries within a certain time, so some have had issues where multiple deliveries were submitet unknowingly. One student suddenly had more than 40 deliveries within a few seconds because of issues with the browser or server.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
