### ISSUE TITLE
Enable students to choose their examiner and group

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#71]
We should have some way of allowing students to choose their own groups and examiner, coupled with a way to set maximum number of groups per examiner. Random distribute should integrate with this to make it easy to distribute those who do not choose an examiner themselves.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
