### ISSUE TITLE
Publish feedback only allowed for admins

### ISSUE THREAD

**Issue by bendikro** [devilry/devilry-django#80]
There should be a setting to allow only admins to publish feedbacks. This would be useful for e.g. home exams where the feedbacks should be published simultaneously for all students.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
