### ISSUE TITLE
Anonymity of tarballs

### ISSUE THREAD

**Issue by ivarref** [devilry/devilry-django#81]
When downloading a full tarball, one can view the who created the single tarballs with
tar tvf candnumber.tar.gz (or similar).

Assuming they packed it on a UiO-machine. The user information should be wiped/anonymized..

PS! Keep up the good work!

Sorry for the bad English.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
