### ISSUE TITLE
Warning when including "personal" information

### ISSUE THREAD

**Issue by ivarref** [devilry/devilry-django#82]
Hi,

how about adding a warning if personal information (username) is included in the feedback?
This would be relative to the correctors, obviously.

Example: Valgrind can give this information, where xxx is the corrector's username:
==zzz== Thread 1:
==zzz== Invalid write of size 1
==zzz==    by 0xcafef00d: somefn (in /blabla/xxx/meh)

Thanks!

Ironically I had to edit this issue in order to not give out information a student could identify..

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
