### ISSUE TITLE
candidate-id missing on all deliveries (current online version)

### ISSUE THREAD

**Issue by andeplane** [devilry/devilry-django#823]
In FYS3150 on devilry, there is currently candidate-id missing on all deliveries after, and including project 4. 

Example (assuming you have access as admin or something): 
https://devilry.ifi.uio.no/devilry_examiner/allgroupsoverview/2065/waiting_for_feedback

**Comment by espenak** [comment]
This is because someone has made the assignment anonymous, and no candidate IDs (kandidatnummer) has been imported. The course teacher must contact devilry-support@ifi.uio.no to get help importing the candidate IDs from FS.

As a sidenote: This is handled with a fallback to a random generated and readable anonymous ID in Devilry 3.0 (will be released jan 2016) - #789.

**Comment by andeplane** [comment]
Great! Thanks :)
