### ISSUE TITLE
Cannot upload empty files

### ISSUE THREAD

**Issue by brkalmar** [devilry/devilry-django#896]
Attempting to upload an empty file (that is to say, a file containing 0 bytes) results in a red X being displayed instead of the uploaded file, and the file is not uploaded:
![devilry-empty-file-1](https://cloud.githubusercontent.com/assets/6377138/19419419/579f37ba-93d7-11e6-9c72-03d06440e788.png)

Same thing happens when I attempt to upload multiple files, and one of them is empty, except with multiple red X-es:
![devilry-empty-file-2](https://cloud.githubusercontent.com/assets/6377138/19419426/987d4394-93d7-11e6-94c4-910b06d37356.png)

This only happens with empty files as far as I can ascertain.

**Comment by torgeirl** [comment]
Thanks for reporting this issue, and apologizes for not getting an answer before now.

I'm not sure how this was intended to work in Devilry v2.x, but we currently (v5.3) display an error for empty files and that is intentional:

![Screenshot from 2022-01-21 13-38-02](https://user-images.githubusercontent.com/796053/150528505-621a0a2d-1fe8-42d5-966d-b94f8db878a6.png)

There are scenarios where for instance the implementation of a Python package could require a `__init__.py` that doesn't need to contain a single line, but we rather force a line in empty files than to risk that students uploading the wrong, empty files for an assignment and will leave it as-is.
