### ISSUE TITLE
Per-examiner feedback

### ISSUE THREAD

**Issue by lexnederbragt** [devilry/devilry-django#920]
We had an issue where it was important for the course director to be able to quickly go over all the feedback from one examiner. This turned out to be cumbersome.

* select oblig
* select all students with that examiner and feedback
* select one of these students and read the feedback
* repeat the entire procedure

Could there be made an easier way, one page that lists all assignments from one examiner, for example?

**Comment by torgeirl** [comment]
This issue was created when Devilry 2.x was the current release and the user interface have been drastically changed since so I'm not sure how relevant it is. In addition, the current administrator view for an assignment when combining the two filters activity=`Has comment(s) from examiner` and Examiner=`Name of examiner` more or less covers this use-case.
