### ISSUE TITLE
Add (simple) footer option

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#931]
**Description**
We should add an option to enable a footer containing links to sites for support, privacy, etc.

**Schedule**
3.0 milestone (January 2018)

**Comment by espenak** [comment]
Fixed in the `issue-932-django1.11` branch.

A guide has been added to the sysadmin documentation: https://github.com/devilry/devilry-django/blob/3af737fdbff60375987a4d5985dd52015cd3824d/not_for_deploy/docs/sysadmin/branding.rst (will become part of the official docs as soon as the branch is merged into master).

Developers can test this out by commenting in the lines with `add_custom_templates_directory` in ``devilry/project/develop/settings/develop.py``. Working examples in ``not_for_deploy/custom_devilry_templates_example/``.

Some examples (note that styles can be adjusted, and that is documented in the guide)

![image](https://user-images.githubusercontent.com/84501/35111710-26ee9214-fc7c-11e7-85ce-a24f922ebf15.png)

![image](https://user-images.githubusercontent.com/84501/35111677-0df0b5f8-fc7c-11e7-93b7-1654e2a5c9c2.png)

![image](https://user-images.githubusercontent.com/84501/35111726-33457ac8-fc7c-11e7-8b6e-af3243e1a6e9.png)
