### ISSUE TITLE
Invisible boundary for assignments during future semesters

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#936]
For a semester set in the future (for testing purposes) there's an unexplained date error when you try to set up an assignment in Devilry3.

For a semester set to the Spring of 2019 (01-01-2019 to 31-07-2019) the boundaries is clearly within those dates (you otherwise get an error stating that the assignment have to fall within that windows), but within that window you get the message "Please fix the errors in the form below" without any errors being highlighted: 
![screenshot from 2018-01-23 11-38-23](https://user-images.githubusercontent.com/796053/35271525-b2c0f12e-0032-11e8-900b-d752bb81393b.png)

If the semester is changed to 2018 (now) everything works fine.

**Suggested fixes**
Display an error to the user (easiest), or remove the boundary as long as assignment fall within the defined semester (preferred).

**Comment by espenak** [comment]
Could you take a look at this and find the root cause for the error @jimma1. Just changing the query may affect other views, so it may not be as simple as just removing the boundary.

**Comment by jimma1** [comment]
Yes, I will @espenak

**Comment by jimma1** [comment]
The root cause was how publishing time was sat in a hidden form field. Publishing time was sat with timezone.now() and a delay of 60 minutes. However the Assignment model demands that publishing time must be within the semester period. I make a pull request to you, @espenak , with a fix that extends the current clean method to also check if semester start time is greater than now.
