### ISSUE TITLE
Let students delete a delivery within a specified time limit

### ISSUE THREAD

**Issue by bendikro** [devilry/devilry-django#96]
Have a configurable time period where the student that delivered the assignment can delete the delivery. This will be useful when a student accidentally delivers wrong files.

Either allow only the student that delivered the delivery, or let every member of the assignmentgroup delete the delivery.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
