### ISSUE TITLE
Make a comment on deliveries

### ISSUE THREAD

**Issue by bendikro** [devilry/devilry-django#97]
The student should be able to include a comment for each delivery. 

Examples are:
- "Disregard previous deliveries. This one should be perfect"
- "I know this is past the deadline, but the last delivery was missing some files."
- "Can you take a look at this issue I have with the file filename.extension? I can't figure out why it almost blew up my computer".

We need a comment system where students, examiners and admins can communicate. I propose a system with several visibility settings, so you can choose to communicate with other examiners, other students in your group, or student-to-examiner. Student-to-examiner should probably be the default.

This will make it easier for multiple examiners to correct the same delivery even when the grade-plugin does not support such a workflow, and it will make it easy for examiners to communicate with their students even when the assignment is anonymous.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
